server:
  port: 8772

spring:
  application:
    name: borrowService
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: true
        cluster-name: Nanjing
        # 添加namespace 隔离生产环境与测试环境
        # namespace: 2c87b8d3-214c-4179-84e9-848f981c1b7d
    loadbalancer:
      nacos:
        enabled: true
    # 添加 sentinel
    sentinel:
      transport:
        dashboard: localhost:8858
      block-page: /dbBorrow/blocked
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy
    password: 123
    username: root